# Generated by Django 4.1.7 on 2023-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_name_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Контактный номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=50, verbose_name='Улица'),
        ),
    ]
